"""Database package initialization."""
from app.db.database import engine, AsyncSessionLocal, get_session, init_db, drop_db, Base
from app.db.models import (
    Agent,
    AgentStatus,
    Project,
    Task,
    Message,
    Decision,
    KnowledgeBase,
    Escalation,
    AuditLog,
    HumanInteraction,
    ProjectStatus,
    TaskStatus,
    Priority,
    MessageType,
    MessageStatus,
    Availability,
)

# Import escalation models
from app.db.escalation_models import (
    AdvancedEscalation,
    EscalationTimelineEvent,
    EscalationComment,
    EscalationNotification,
    EscalationCollaboration,
    EscalationSLAConfig,
    EscalationTemplate,
    EscalationPlaybook,
    EscalationWatchlist,
    EscalationAnalytics,
    EscalationType,
    EscalationPriority,
    EscalationStatus,
    EscalationLevel,
    ResolutionType,
    ImpactLevel,
    UrgencyLevel,
    EscalationEventType,
)

# Import conversation models
from app.db.conversation_models import (
    Conversation,
    ConversationMessage,
    ConversationParticipant,
    ConversationTopic,
    ProjectCreationIntent,
    ConversationAnalytics,
    ConversationType,
    ConversationStatus,
    SenderType,
    ContentType,
    MessageTypeConversation,
    ParticipantType,
    ParticipantRole,
    ProjectIntentStatus,
    UserResponse,
)

__all__ = [
    "engine",
    "AsyncSessionLocal",
    "get_session",
    "init_db",
    "drop_db",
    "Base",
    "Agent",
    "AgentStatus",
    "Project",
    "Task",
    "Message",
    "Decision",
    "KnowledgeBase",
    "Escalation",
    "AuditLog",
    "HumanInteraction",
    "ProjectStatus",
    "TaskStatus",
    "Priority",
    "MessageType",
    "MessageStatus",
    "Availability",
    # Escalation models
    "AdvancedEscalation",
    "EscalationTimelineEvent",
    "EscalationComment",
    "EscalationNotification",
    "EscalationCollaboration",
    "EscalationSLAConfig",
    "EscalationTemplate",
    "EscalationPlaybook",
    "EscalationWatchlist",
    "EscalationAnalytics",
    "EscalationType",
    "EscalationPriority",
    "EscalationStatus",
    "EscalationLevel",
    "ResolutionType",
    "ImpactLevel",
    "UrgencyLevel",
    "EscalationEventType",
    # Conversation models
    "Conversation",
    "ConversationMessage",
    "ConversationParticipant",
    "ConversationTopic",
    "ProjectCreationIntent",
    "ConversationAnalytics",
    "ConversationType",
    "ConversationStatus",
    "SenderType",
    "ContentType",
    "MessageTypeConversation",
    "ParticipantType",
    "ParticipantRole",
    "ProjectIntentStatus",
    "UserResponse",
]
