"""init vv1

Revision ID: 7094a0d12afb
Revises: 004_phase2_analytics
Create Date: 2025-11-23 17:25:31.108133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7094a0d12afb'
down_revision: Union[str, Sequence[str], None] = '004_phase2_analytics'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_environments_project_id'), table_name='deployment_environments')
    op.drop_table('deployment_environments')
    op.drop_index(op.f('ix_content_generations_agent_id'), table_name='content_generations')
    op.drop_index(op.f('ix_content_generations_project_id'), table_name='content_generations')
    op.drop_index(op.f('ix_content_generations_started_at'), table_name='content_generations')
    op.drop_table('content_generations')
    op.drop_table('export_templates')
    op.drop_table('platform_connections')
    op.drop_table('deployments')
    op.drop_index(op.f('idx_agent_thoughts_project_created'), table_name='agent_thoughts')
    op.drop_index(op.f('ix_agent_thoughts_agent_id'), table_name='agent_thoughts')
    op.drop_index(op.f('ix_agent_thoughts_created_at'), table_name='agent_thoughts')
    op.drop_index(op.f('ix_agent_thoughts_project_id'), table_name='agent_thoughts')
    op.drop_table('agent_thoughts')
    op.drop_table('project_deployments')
    op.drop_table('export_jobs')
    op.drop_index(op.f('idx_agent_handoffs_project_initiated'), table_name='agent_handoffs')
    op.drop_index(op.f('idx_agent_handoffs_to_agent_status'), table_name='agent_handoffs')
    op.drop_index(op.f('ix_agent_handoffs_from_agent_id'), table_name='agent_handoffs')
    op.drop_index(op.f('ix_agent_handoffs_initiated_at'), table_name='agent_handoffs')
    op.drop_index(op.f('ix_agent_handoffs_project_id'), table_name='agent_handoffs')
    op.drop_index(op.f('ix_agent_handoffs_to_agent_id'), table_name='agent_handoffs')
    op.drop_table('agent_handoffs')
    op.drop_table('task_feedback')
    op.drop_table('agent_feedback')
    op.drop_table('deployment_logs')
    op.drop_index(op.f('ix_decision_points_agent_id'), table_name='decision_points')
    op.drop_index(op.f('ix_decision_points_created_at'), table_name='decision_points')
    op.drop_index(op.f('ix_decision_points_project_id'), table_name='decision_points')
    op.drop_table('decision_points')
    op.drop_table('export_cache')
    op.drop_index(op.f('idx_agent_activities_agent_active'), table_name='agent_activities')
    op.drop_index(op.f('idx_agent_activities_project_created'), table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_agent_id'), table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_created_at'), table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_project_id'), table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_task_id'), table_name='agent_activities')
    op.drop_table('agent_activities')
    op.drop_table('zip_export_options')
    op.drop_index(op.f('idx_event_timeline_highlights'), table_name='event_timeline')
    op.drop_index(op.f('idx_event_timeline_project_timestamp'), table_name='event_timeline')
    op.drop_index(op.f('ix_event_timeline_event_timestamp'), table_name='event_timeline')
    op.drop_index(op.f('ix_event_timeline_event_type'), table_name='event_timeline')
    op.drop_index(op.f('ix_event_timeline_project_id'), table_name='event_timeline')
    op.drop_table('event_timeline')
    op.drop_table('agent_platform_connections')
    op.drop_table('context_updates')
    op.drop_table('system_learning')
    op.drop_table('project_feedback')
    op.drop_index(op.f('idx_llm_interactions_project_started'), table_name='llm_interactions')
    op.drop_index(op.f('ix_llm_interactions_agent_id'), table_name='llm_interactions')
    op.drop_index(op.f('ix_llm_interactions_project_id'), table_name='llm_interactions')
    op.drop_index(op.f('ix_llm_interactions_started_at'), table_name='llm_interactions')
    op.drop_table('llm_interactions')
    op.drop_index(op.f('ix_agent_metrics_agent_id'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_metric_date'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_project_id'), table_name='agent_metrics')
    op.drop_table('agent_metrics')
    op.alter_column('agent_performance_metrics', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_agent_performance_agent_id'), table_name='agent_performance_metrics')
    op.drop_index(op.f('idx_agent_performance_project_id'), table_name='agent_performance_metrics')
    op.drop_index(op.f('idx_agent_performance_task_id'), table_name='agent_performance_metrics')
    op.alter_column('agent_skill_progression', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_agent_skill_progression_agent_id'), table_name='agent_skill_progression')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('idx_deliverable_active'), table_name='deliverable_types')
    op.drop_index(op.f('idx_department_active'), table_name='departments')
    op.drop_index(op.f('idx_agent_projects'), table_name='project_agent_assignments')
    op.drop_index(op.f('idx_project_agent_assignments_active'), table_name='project_agent_assignments')
    op.drop_index(op.f('idx_project_agent_assignments_assigned'), table_name='project_agent_assignments')
    op.drop_index(op.f('idx_project_agents'), table_name='project_agent_assignments')
    op.drop_constraint(op.f('uq_project_agent'), 'project_agent_assignments', type_='unique')
    op.alter_column('project_metrics', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_project_metrics_project_id'), table_name='project_metrics')
    op.drop_index(op.f('idx_projects_deliverable_type'), table_name='projects')
    op.drop_index(op.f('idx_projects_project_type'), table_name='projects')
    op.alter_column('task_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_task_templates_project_type'), table_name='task_templates')
    op.drop_index(op.f('idx_tasks_output_format'), table_name='tasks')
    op.alter_column('workflow_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_workflow_instances_project_id'), table_name='workflow_instances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_workflow_instances_project_id'), 'workflow_instances', ['project_id'], unique=False)
    op.alter_column('workflow_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_tasks_output_format'), 'tasks', ['output_format'], unique=False)
    op.create_index(op.f('idx_task_templates_project_type'), 'task_templates', ['project_type'], unique=False)
    op.alter_column('task_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_index(op.f('idx_projects_deliverable_type'), 'projects', ['deliverable_type'], unique=False)
    op.create_index(op.f('idx_project_metrics_project_id'), 'project_metrics', ['project_id'], unique=False)
    op.alter_column('project_metrics', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('uq_project_agent'), 'project_agent_assignments', ['project_id', 'agent_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_project_agents'), 'project_agent_assignments', ['project_id'], unique=False)
    op.create_index(op.f('idx_project_agent_assignments_assigned'), 'project_agent_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('idx_project_agent_assignments_active'), 'project_agent_assignments', ['is_active'], unique=False)
    op.create_index(op.f('idx_agent_projects'), 'project_agent_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('idx_department_active'), 'departments', ['is_active'], unique=False)
    op.create_index(op.f('idx_deliverable_active'), 'deliverable_types', ['is_active'], unique=False)
    op.create_index(op.f('idx_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_agent_skill_progression_agent_id'), 'agent_skill_progression', ['agent_id'], unique=False)
    op.alter_column('agent_skill_progression', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_agent_performance_task_id'), 'agent_performance_metrics', ['task_id'], unique=False)
    op.create_index(op.f('idx_agent_performance_project_id'), 'agent_performance_metrics', ['project_id'], unique=False)
    op.create_index(op.f('idx_agent_performance_agent_id'), 'agent_performance_metrics', ['agent_id'], unique=False)
    op.alter_column('agent_performance_metrics', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('agent_metrics',
    sa.Column('metric_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tasks_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tasks_in_progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_completion_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('llm_calls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('active_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idle_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metric_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('agent_metrics_agent_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('agent_metrics_project_id_fkey')),
    sa.PrimaryKeyConstraint('metric_id', name=op.f('agent_metrics_pkey'))
    )
    op.create_index(op.f('ix_agent_metrics_project_id'), 'agent_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_metrics_metric_date'), 'agent_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_agent_metrics_agent_id'), 'agent_metrics', ['agent_id'], unique=False)
    op.create_table('llm_interactions',
    sa.Column('interaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider', postgresql.ENUM('ANTHROPIC', 'OPENAI', 'GOOGLE', 'LOCAL', name='llmprovider'), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('finish_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['agent_activities.activity_id'], name=op.f('llm_interactions_activity_id_fkey')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('llm_interactions_agent_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('llm_interactions_project_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('llm_interactions_task_id_fkey')),
    sa.PrimaryKeyConstraint('interaction_id', name=op.f('llm_interactions_pkey'))
    )
    op.create_index(op.f('ix_llm_interactions_started_at'), 'llm_interactions', ['started_at'], unique=False)
    op.create_index(op.f('ix_llm_interactions_project_id'), 'llm_interactions', ['project_id'], unique=False)
    op.create_index(op.f('ix_llm_interactions_agent_id'), 'llm_interactions', ['agent_id'], unique=False)
    op.create_index(op.f('idx_llm_interactions_project_started'), 'llm_interactions', ['project_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('project_feedback',
    sa.Column('feedback_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feedback_type', postgresql.ENUM('GENERAL', 'QUALITY', 'CORRECTNESS', 'COMPLETENESS', 'DIRECTION', 'IMPLEMENTATION', 'BLOCKING_ISSUE', 'ENHANCEMENT', 'BUG_REPORT', 'PERFORMANCE', name='feedbacktype'), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('USER', 'SYSTEM', 'AGENT_REVIEW', 'AUTOMATED', name='feedbacksource'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACKNOWLEDGED', 'IN_PROGRESS', 'IMPLEMENTED', 'RESOLVED', 'REJECTED', 'ARCHIVED', name='feedbackstatus'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('quality_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('satisfaction_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('suggested_actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('assigned_to_agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('implementation_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('implemented_changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_agent_id'], ['agents.agent_id'], name=op.f('project_feedback_assigned_to_agent_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('project_feedback_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('project_feedback_pkey'))
    )
    op.create_table('system_learning',
    sa.Column('learning_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('learning_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_feedback_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('affected_agent_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('affected_task_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('proposed_solution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('implementation_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_prompt_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('configuration_changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tested', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('effectiveness_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('learning_id', name=op.f('system_learning_pkey'))
    )
    op.create_table('context_updates',
    sa.Column('context_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context_tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_by_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('related_feedback_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('referenced_by_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('implementation_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('related_agent_updates', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('context_id', name=op.f('context_updates_pkey'))
    )
    op.create_table('agent_platform_connections',
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('platform_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('platform_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('platform_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connected_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('agent_platform_connections_agent_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id', name=op.f('agent_platform_connections_pkey'))
    )
    op.create_table('event_timeline',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('related_activity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('related_task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_highlight', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('highlight_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('event_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('event_timeline_agent_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('event_timeline_project_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('event_timeline_pkey'))
    )
    op.create_index(op.f('ix_event_timeline_project_id'), 'event_timeline', ['project_id'], unique=False)
    op.create_index(op.f('ix_event_timeline_event_type'), 'event_timeline', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_timeline_event_timestamp'), 'event_timeline', ['event_timestamp'], unique=False)
    op.create_index(op.f('idx_event_timeline_project_timestamp'), 'event_timeline', ['project_id', sa.literal_column('event_timestamp DESC')], unique=False)
    op.create_index(op.f('idx_event_timeline_highlights'), 'event_timeline', ['project_id', 'is_highlight'], unique=False)
    op.create_table('zip_export_options',
    sa.Column('option_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('include_source_code', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_tests', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_documentation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_assets', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_database_schema', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_docker_config', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_ci_cd_config', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_agentgo_metadata', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_env_example', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('format_code', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fix_linting_issues', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('documentation_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('generate_setup_script', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('compression_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_size_estimate_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['export_jobs.job_id'], name=op.f('zip_export_options_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id', name=op.f('zip_export_options_pkey'))
    )
    op.create_table('agent_activities',
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('activity_type', postgresql.ENUM('THINKING', 'GENERATING', 'WAITING', 'DECIDING', 'MESSAGING', 'EXECUTING', 'REVIEWING', 'COMPLETED', 'ERROR', name='activitytype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name='agent_activities_agent_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name='agent_activities_project_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name='agent_activities_task_id_fkey'),
    sa.PrimaryKeyConstraint('activity_id', name='agent_activities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_agent_activities_task_id'), 'agent_activities', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_activities_project_id'), 'agent_activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_activities_created_at'), 'agent_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_activities_agent_id'), 'agent_activities', ['agent_id'], unique=False)
    op.create_index(op.f('idx_agent_activities_project_created'), 'agent_activities', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_activities_agent_active'), 'agent_activities', ['agent_id', 'is_active'], unique=False)
    op.create_table('export_cache',
    sa.Column('cache_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('export_format', postgresql.ENUM('PDF', 'MARKDOWN', 'ZIP', name='exportformat'), autoincrement=False, nullable=False),
    sa.Column('export_type', postgresql.ENUM('PROJECT_SUMMARY', 'FULL_DOCUMENTATION', 'TASK_REPORT', 'AGENT_ACTIVITY_REPORT', 'CODE_DOCUMENTATION', 'ANALYTICS_METRICS', 'CUSTOM', 'PROJECT_FILES_ZIP', name='exporttype'), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['original_job_id'], ['export_jobs.job_id'], name=op.f('export_cache_original_job_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('export_cache_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cache_id', name=op.f('export_cache_pkey')),
    sa.UniqueConstraint('data_hash', name=op.f('export_cache_data_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('decision_points',
    sa.Column('decision_point_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('decision_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pros_cons', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('impact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('requires_approval', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('approval_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('chosen_option', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['agent_activities.activity_id'], name=op.f('decision_points_activity_id_fkey')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('decision_points_agent_id_fkey')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], name=op.f('decision_points_decision_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('decision_points_project_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('decision_points_task_id_fkey')),
    sa.PrimaryKeyConstraint('decision_point_id', name=op.f('decision_points_pkey'))
    )
    op.create_index(op.f('ix_decision_points_project_id'), 'decision_points', ['project_id'], unique=False)
    op.create_index(op.f('ix_decision_points_created_at'), 'decision_points', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_points_agent_id'), 'decision_points', ['agent_id'], unique=False)
    op.create_table('deployment_logs',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('log_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.deployment_id'], name=op.f('deployment_logs_deployment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('deployment_logs_pkey'))
    )
    op.create_table('agent_feedback',
    sa.Column('feedback_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('related_task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('related_project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('feedback_type', postgresql.ENUM('GENERAL', 'QUALITY', 'CORRECTNESS', 'COMPLETENESS', 'DIRECTION', 'IMPLEMENTATION', 'BLOCKING_ISSUE', 'ENHANCEMENT', 'BUG_REPORT', 'PERFORMANCE', name='feedbacktype'), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('USER', 'SYSTEM', 'AGENT_REVIEW', 'AUTOMATED', name='feedbacksource'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACKNOWLEDGED', 'IN_PROGRESS', 'IMPLEMENTED', 'RESOLVED', 'REJECTED', 'ARCHIVED', name='feedbackstatus'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('decision_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('communication_clarity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('problem_solving', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('efficiency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('behavior_observations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommended_improvements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strengths_noted', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('suggested_system_prompt_updates', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('acknowledged_by_system', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('system_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('agent_feedback_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.project_id'], name=op.f('agent_feedback_related_project_id_fkey')),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.task_id'], name=op.f('agent_feedback_related_task_id_fkey')),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('agent_feedback_pkey'))
    )
    op.create_table('task_feedback',
    sa.Column('feedback_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feedback_type', postgresql.ENUM('GENERAL', 'QUALITY', 'CORRECTNESS', 'COMPLETENESS', 'DIRECTION', 'IMPLEMENTATION', 'BLOCKING_ISSUE', 'ENHANCEMENT', 'BUG_REPORT', 'PERFORMANCE', name='feedbacktype'), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('USER', 'SYSTEM', 'AGENT_REVIEW', 'AUTOMATED', name='feedbacksource'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACKNOWLEDGED', 'IN_PROGRESS', 'IMPLEMENTED', 'RESOLVED', 'REJECTED', 'ARCHIVED', name='feedbackstatus'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correctness', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completeness', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('implementation_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code_review_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggested_improvements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('assigned_to_agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('implementation_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changes_made', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_agent_id'], ['agents.agent_id'], name=op.f('task_feedback_assigned_to_agent_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('task_feedback_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('task_feedback_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('task_feedback_pkey'))
    )
    op.create_table('agent_handoffs',
    sa.Column('handoff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('to_agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('handoff_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('INITIATED', 'IN_TRANSIT', 'RECEIVED', 'ACCEPTED', 'REJECTED', name='handoffstatus'), autoincrement=False, nullable=False),
    sa.Column('initiated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.agent_id'], name=op.f('agent_handoffs_from_agent_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('agent_handoffs_project_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('agent_handoffs_task_id_fkey')),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.agent_id'], name=op.f('agent_handoffs_to_agent_id_fkey')),
    sa.PrimaryKeyConstraint('handoff_id', name=op.f('agent_handoffs_pkey'))
    )
    op.create_index(op.f('ix_agent_handoffs_to_agent_id'), 'agent_handoffs', ['to_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_handoffs_project_id'), 'agent_handoffs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_handoffs_initiated_at'), 'agent_handoffs', ['initiated_at'], unique=False)
    op.create_index(op.f('ix_agent_handoffs_from_agent_id'), 'agent_handoffs', ['from_agent_id'], unique=False)
    op.create_index(op.f('idx_agent_handoffs_to_agent_status'), 'agent_handoffs', ['to_agent_id', 'status'], unique=False)
    op.create_index(op.f('idx_agent_handoffs_project_initiated'), 'agent_handoffs', ['project_id', sa.literal_column('initiated_at DESC')], unique=False)
    op.create_table('export_jobs',
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('export_format', postgresql.ENUM('PDF', 'MARKDOWN', 'ZIP', name='exportformat'), autoincrement=False, nullable=False),
    sa.Column('export_type', postgresql.ENUM('PROJECT_SUMMARY', 'FULL_DOCUMENTATION', 'TASK_REPORT', 'AGENT_ACTIVITY_REPORT', 'CODE_DOCUMENTATION', 'ANALYTICS_METRICS', 'CUSTOM', 'PROJECT_FILES_ZIP', name='exporttype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'GATHERING_DATA', 'RENDERING', 'GENERATING', 'COMPLETED', 'FAILED', 'CANCELLED', name='exportstatus'), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('download_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estimated_completion_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by_agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('is_cached', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cache_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.agent_id'], name=op.f('export_jobs_created_by_agent_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('export_jobs_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('export_jobs_pkey'))
    )
    op.create_table('project_deployments',
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('deployment_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('github_repo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('github_repo_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vercel_deployment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vercel_project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'UPLOADING', 'BUILDING', 'DEPLOYING', 'SUCCESS', 'FAILED', 'CANCELLED', name='deploymentstatus'), autoincrement=False, nullable=True),
    sa.Column('build_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deployed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deployment_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('project_deployments_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deployment_id', name=op.f('project_deployments_pkey'))
    )
    op.create_table('agent_thoughts',
    sa.Column('thought_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('thought_type', postgresql.ENUM('ANALYSIS', 'PLANNING', 'REASONING', 'EVALUATION', 'REFLECTION', name='thoughttype'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['agent_activities.activity_id'], name=op.f('agent_thoughts_activity_id_fkey')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('agent_thoughts_agent_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('agent_thoughts_project_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('agent_thoughts_task_id_fkey')),
    sa.PrimaryKeyConstraint('thought_id', name=op.f('agent_thoughts_pkey'))
    )
    op.create_index(op.f('ix_agent_thoughts_project_id'), 'agent_thoughts', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_thoughts_created_at'), 'agent_thoughts', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_thoughts_agent_id'), 'agent_thoughts', ['agent_id'], unique=False)
    op.create_index(op.f('idx_agent_thoughts_project_created'), 'agent_thoughts', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('deployments',
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'UPLOADING', 'BUILDING', 'DEPLOYING', 'SUCCESS', 'FAILED', 'CANCELLED', name='deploymentstatus'), autoincrement=False, nullable=False),
    sa.Column('environment', postgresql.ENUM('DEVELOPMENT', 'STAGING', 'PRODUCTION', name='deploymentenvironment'), autoincrement=False, nullable=True),
    sa.Column('deployment_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('build_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('build_logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('git_commit_sha', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('git_branch', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deployed_by_agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('previous_deployment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_rollback', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deployed_by_agent_id'], ['agents.agent_id'], name=op.f('deployments_deployed_by_agent_id_fkey')),
    sa.ForeignKeyConstraint(['previous_deployment_id'], ['deployments.deployment_id'], name=op.f('deployments_previous_deployment_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('deployments_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deployment_id', name=op.f('deployments_pkey'))
    )
    op.create_table('platform_connections',
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('platform_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('platform_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('platform_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connected_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('platform_connections_agent_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id', name=op.f('platform_connections_pkey'))
    )
    op.create_table('export_templates',
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('export_type', postgresql.ENUM('PROJECT_SUMMARY', 'FULL_DOCUMENTATION', 'TASK_REPORT', 'AGENT_ACTIVITY_REPORT', 'CODE_DOCUMENTATION', 'ANALYTICS_METRICS', 'CUSTOM', 'PROJECT_FILES_ZIP', name='exporttype'), autoincrement=False, nullable=False),
    sa.Column('export_format', postgresql.ENUM('PDF', 'MARKDOWN', 'ZIP', name='exportformat'), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('styling', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by_agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.agent_id'], name=op.f('export_templates_created_by_agent_id_fkey')),
    sa.PrimaryKeyConstraint('template_id', name=op.f('export_templates_pkey'))
    )
    op.create_table('content_generations',
    sa.Column('generation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_chunks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tokens_generated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['agent_activities.activity_id'], name=op.f('content_generations_activity_id_fkey')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('content_generations_agent_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('content_generations_project_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('content_generations_task_id_fkey')),
    sa.PrimaryKeyConstraint('generation_id', name=op.f('content_generations_pkey'))
    )
    op.create_index(op.f('ix_content_generations_started_at'), 'content_generations', ['started_at'], unique=False)
    op.create_index(op.f('ix_content_generations_project_id'), 'content_generations', ['project_id'], unique=False)
    op.create_index(op.f('ix_content_generations_agent_id'), 'content_generations', ['agent_id'], unique=False)
    op.create_table('deployment_environments',
    sa.Column('env_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('environment_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('deployment_environments_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('env_id', name=op.f('deployment_environments_pkey'))
    )
    op.create_index(op.f('ix_deployment_environments_project_id'), 'deployment_environments', ['project_id'], unique=False)
    # ### end Alembic commands ###
